### ISSUE TITLE
PlotSquared 7 support is broken

### ISSUE THREAD

**Issue by ChimpGamer** [Ste3et/ProtectionLib#13]
The PlotSquared 7 hook is broken after the PlotSquared 7.3.8 update I think. I'm running the latest snapshot of 7.3.10 at the moment.

I'm running Paper 1.21 with ProtectionLib 1.8.4 and FurnitureLib 3.2.2

```
[07:00:23] [Server thread/INFO]: [ProtectionLib] Loading server plugin ProtectionLib v1.8.4
[07:00:23] [Server thread/INFO]: [ProtectionLib] ProtectionLib-Module: LocalLibary hooked!
[07:00:23] [Server thread/INFO]: [ProtectionLib] ProtectionLib-Module: PlotSquaredV3Module hooked!
[07:00:23] [Server thread/INFO]: [ProtectionLib] ProtectionLib-Module: PlotSquaredV4Module hooked!
[07:00:23] [Server thread/INFO]: [ProtectionLib] ProtectionLib-Module: PlotSquaredV6Module hooked!
[07:00:23] [Server thread/INFO]: [ProtectionLib] ProtectionLib-Module: PlotSquaredV7Module hooked!
[07:00:23] [Server thread/INFO]: [ProtectionLib] fPlotSquaredV7 try to hook into PlotSquared
[07:00:23] [Server thread/INFO]: [ProtectionLib] ProtectionClass: fPlotSquaredV7 throw an Exception!
[07:00:23] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[07:00:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)
[07:00:23] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[07:00:23] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[07:00:23] [Server thread/WARN]: 	at ProtectionLib-v1.8.4.jar//de.Ste3et_C0st.ProtectionLib.main.ProtectionLib.lambda$hookIntoPlugins$4(ProtectionLib.java:96)
[07:00:23] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[07:00:23] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[07:00:23] [Server thread/WARN]: 	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1858)
[07:00:23] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[07:00:23] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[07:00:23] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[07:00:23] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[07:00:23] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[07:00:23] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[07:00:23] [Server thread/WARN]: 	at ProtectionLib-v1.8.4.jar//de.Ste3et_C0st.ProtectionLib.main.ProtectionLib.hookIntoPlugins(ProtectionLib.java:91)
[07:00:23] [Server thread/WARN]: 	at ProtectionLib-v1.8.4.jar//de.Ste3et_C0st.ProtectionLib.main.ProtectionLib.addWatchers(ProtectionLib.java:84)
[07:00:23] [Server thread/WARN]: 	at ProtectionLib-v1.8.4.jar//de.Ste3et_C0st.ProtectionLib.main.ProtectionLib.onLoad(ProtectionLib.java:76)
[07:00:23] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[07:00:23] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[07:00:23] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[07:00:23] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
[07:00:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
[07:00:23] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
[07:00:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[07:00:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[07:00:23] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[07:00:23] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "com.plotsquared.core.PlotSquared.getEventDispatcher()" because the return value of "com.plotsquared.core.PlotSquared.get()" is null
[07:00:23] [Server thread/WARN]: 	at plotsquared-bukkit-v7.3.10-SNAPSHOT-b19.jar//com.plotsquared.core.PlotAPI.registerListener(PlotAPI.java:206)
[07:00:23] [Server thread/WARN]: 	at ProtectionLib-v1.8.4.jar//de.Ste3et_C0st.ProtectionLib.main.plugins.fPlotSquaredV7.<init>(fPlotSquaredV7.java:28)
[07:00:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[07:00:23] [Server thread/WARN]: 	... 24 more
```

**Comment by Ste3et** [comment]
Thank you i will take a look into it asap but atm im very busy and have not a mutch time

**Comment by Ste3et** [comment]
Can you try these devbuild https://dicecraft.de/furniture/download.php?plugin=ProtectionLib&build=DevBuild&version=Spigot%201.12.x%20-%201.20.x&commit=70b655ff ?

**Comment by ChimpGamer** [comment]
Looks like it's fixed with that build. No more errors regarding ProtectionLib and PlotSquared. Thanks!
